{{- $root := . }}
{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "application.labels" $root | nindent 4 }}
  {{- with $root.Values.configmapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
